### ISSUE TITLE
ORC Reader missing files or rows when running Queries

### ISSUE THREAD

**Issue by felipeblazing** [BlazingDB/blazingdb-ral#150] opened 2019-09-13 00:38 UTC
from blazingsql import BlazingContext
bc = BlazingContext()

df = cudf.read_orc( "some list of files")

bc.create_table('cudf_read',df)
bc.create_table('blazing_read', "same list of files")

result = bc.sql('select count(*) from cudf_read').get()
len(result.columns)  ==> shows some number like 100

result = bc.sql('select count(*) from blazing_read').get()
len(result.columns) ==> shows some number smaller than what the top one outpus

Rows are either being removed or files are being omitted when sending blazing list of orc files.

**Comment by williamBlazing** [comment] 2019-09-13 22:16
Is it possible to get more exact examples or description of the data or how the tables were created? I have not been able to replicate the issue?

Was this run on one or more than one node?

**Comment by mlahir1** [comment] 2019-09-16 14:32
This is run on a single node, with 4 GPU's in it. It has over hundred files provided in the list for read ORC. and the result DF will not fit in a single GPU.

**Comment by williamBlazing** [comment] 2019-09-17 15:25
Ok, so I have several more questions. I am understanding that you tried creating a DataFrame using cudf and then created a table from that DataFrame and queried that table with BlazingSQL and got one result:
```
df = cudf.read_orc( "file")
bc.create_table('cudf_read',df)
result = bc.sql('select count(*) from cudf_read').get()
len(result.columns) ==> shows some number like 100
```

You then compared that with creating a table based off of files and queried that table and got different results.
```
bc.create_table('blazing_read', "same list of files")
result = bc.sql('select count(*) from blazing_read').get()
len(result.columns) ==> shows some number smaller than what the top one outpus
```

Now, if you have multiple files, how did you create the DataFrame using cudf? Did you read each file and concatenate the results?
```
df0 = cudf.read_orc('file0.orc')
df1 = cudf.read_orc('file1.orc')
df= cudf.concat([df0, df1])
```
 You also mention that the resulting DF will not fit in a single GPU, so how did you create the DataFrame?

If you have a single node with 4 GPUs, I am assuming you have 4 BlazingSQL workers? If so, did you create a table from a dataframe and then tried to query it using BlazingSQL with 4 workers? If so, that will not work. Right now the distributed version of our engine does not properly handle querying a data frame that was created with cudf. This is something we are finishing, but it will need to be a daskgdf in order for it to be queried by a distributed BlazingSQL

**Comment by mlahir1** [comment] 2019-09-18 15:19
yes, I read each files and concated the results.

```
li=[]
for f in files:
    li.append(cudf.read_orc(f, columns=['_col0']))
df = cudf.concat(li)
```

since the resulting df did not fit in memory, we s electing a single col from the orc files so that it fits in the memory. even in this case create_table drops rows when trying to create table from list of files.

**If you have a single node with 4 GPUs, I am assuming you have 4 BlazingSQL workers?** 
I am not creating any blazing workers manually. i am just running a blazingContext().

**Comment by aucahuasi** [comment] 2019-09-18 20:42
Hi @mlahir1 

The gdf output  for the SQL statement 'select count(*) from cudf_read' will return the count number (a single entry inside the gdf) and if you perform len(gdf_output) then it will show always 1

If you change the SQL statement to 'select * from cudf_read' and then perform the len operation over that gdf, then should be working fine.

Please let us know if there are more issues here!

cc @rommelDB

**Comment by mlahir1** [comment] 2019-09-18 20:56
@aucahuasi 

Thats not the issue.
'select count(*) from table'/'select* from table'. is giving different results, depending how you make the table,
1. if you do a read_orc and make a cudf df and create pyblazing sql table from that, `select count(*) from table/select * from table` is right and gives same number of results as it is supposed to have.
2. Instead, if you create a table by passing a list of orc files to create a table it shows lesser number of rows in both the queries.

**Comment by aucahuasi** [comment] 2019-09-18 21:40
@mlahir1 Thanks! Let us make a double check again please, we have made some tests but with little orc files and we didn't see that behavior. How many orc files are you using and what is the aprox size? Also is it possible to know what datatypes contains the files?

**Comment by williamBlazing** [comment] 2019-09-23 19:51
Hello @mlahir1 to try to see if there is perhaps a difference in datatypes accross the files you are testing, could you perhaps run this function against your file list:

```
def validate_same_schema(file_list):
    df = cudf.read_orc(file_list[0])
    schema = df.dtypes
    print("File Schema is: ")
    print(schema)
    for file in file_list:
        df = cudf.read_orc(file)
        if not all(schema == df.dtypes):
            print("found file with different schema")
            print("file: " + str(file_list[0]) + " schema: ")
            print(schema)
            print("file: " + str(file) + " schema: ")
            print(df.dtypes)
```

**Comment by mlahir1** [comment] 2019-09-23 20:03
I have changed the function a bit to read the columns that we are using the query.

```
def validate_same_schema(file_list):
    df = cudf.read_orc(file_list[0], columns=['_col0', '_col6', '_col105'])
    schema = df.dtypes
    print("File Schema is: ")
    print(schema)
    for file in file_list:
        df = cudf.read_orc(file, columns=['_col0', '_col6', '_col105'])
        if not all(schema == df.dtypes):
            print("found file with different schema")
            print("file: " + str(file_list[0]) + " schema: ")
            print(schema)
            print("file: " + str(file) + " schema: ")
            print(df.dtypes)
```

output:
```
>>> validate_same_schema(files)
File Schema is: 
_col0               int32
_col6                int8
_col105    datetime64[ns]
dtype: object
```

**Comment by williamBlazing** [comment] 2019-09-23 21:10
Hello @mlahir1 . I have a suspicion that the issue is related to the `datetime64[ns]` column. Could you test the following:

Using the query
query='''
    SELECT _col0, _col6, _col105
    FROM svs
    WHERE _col6 < 4
    '''
What are the number of rows and the output data types that you get if you query a DataFrame Table vs an Orc File Table

**Comment by mlahir1** [comment] 2019-09-23 21:18
i think is is related to that. I have sent it in the email after the meeting. 
Also I have conducted tests with the query.
query='''
    SELECT _col0
    FROM svs
    WHERE _col6 < 4
    AND _col105 <= '2019-07-17 09:00:00'
    '''
result = bc.sql(query).get()
res_gdf = result.columns
print(res_gdf)
>>>18775137
 
If I remove the where _col105 it give 73 million rows.
query='''
    SELECT _col0
    FROM svs
    WHERE _col6 < 4
‘’’

**Comment by mlahir1** [comment] 2019-09-24 15:27
If I run this query
query='''
SELECT _col0
FROM svs
'''
it gives me `73200904` which is same as expected results.
but if I run the below query
query='''
SELECT _col0
FROM svs
WHERE _col6 < 4
AND _col105 <= '2019-07-17 09:00:00'
'''

blazingsql-engine crashes with `Segmentation fault (core dumped)` and an error message: 0
`Unexpected error on _run_query_get_results, can only concatenate str (not "tuple") to str`

**Comment by aucahuasi** [comment] 2019-09-26 17:08
@mlahir1 We have been doing many tests and found that in order to work correctly with orc files we need to upgrade to cudf 0.10. So now we are in the upgrading process, we will get back you soon! +1 cc @Christian8491

**Comment by aucahuasi** [comment] 2019-09-30 19:38
@mlahir1 We are in the middle of upgrade BlazingSQL to cudf 0.10 (many tests pass, we are dealing now with some date issues) as soon as we have the new release we will get back to you! Thanks for wait! +1

**Comment by mlahir1** [comment] 2019-10-07 20:04
@felipeblazing @williamBlazing 

I identified what's the root cause of the issue. if you provide a single file when creating a table it return the right results.
```
>>> import cudf, glob
>>> from blazingsql import BlazingContext
>>> 
>>> 
>>> files = glob.glob('/root/tdata/*')
>>> files
['/root/tdata/test1.orc', '/root/tdata/test2.orc', '/root/tdata/test3.orc', '/root/tdata/test4.orc', '/root/tdata/test5.orc', '/root/tdata/test.orc']
>>> bc= BlazingContext()
connection established
>>> bc.create_table('svs', files[0], file_format='orc')
<pyblazing.apiv2.sql.Table object at 0x7f23508e6a10>
>>> query='''
...     SELECT * FROM svs
...     WHERE _col105 <= TIMESTAMP '2019-08-17 09:00:00'
... '''
>>> 
>>> result = bc.sql(query).get()
>>> res_gdf = result.columns
>>> len(res_gdf)
100
```

I have copied the file multiple times in the same directory. and tried to create a table from all these files not the length of my result is 0.

```
>>> import cudf, glob
>>> from blazingsql import BlazingContext
>>> bc= BlazingContext()
connection established
>>> files = glob.glob('/root/tdata/*')
>>> files
['/root/tdata/test1.orc', '/root/tdata/test2.orc', '/root/tdata/test3.orc', '/root/tdata/test4.orc', '/root/tdata/test5.orc', '/root/tdata/test.orc']
>>> bc.create_table('svs', files, file_format='orc')
<pyblazing.apiv2.sql.Table object at 0x7f48efa0ee90>
>>> query='''
...     SELECT * FROM svs
...     WHERE _col105 <= TIMESTAMP '2019-08-17 09:00:00'
... '''
>>> 
>>> 
>>> result = bc.sql(query).get()
>>> res_gdf = result.columns
>>> len(res_gdf)
0

```

I am also attaching the zipped tdata dir for your reference.
[tdata.tar.gz](https://github.com/BlazingDB/blazingdb-ral/files/3699042/tdata.tar.gz)

**Comment by aucahuasi** [comment] 2019-10-07 20:11
Thanks @mlahir1 We manage to reproduce the issue and perform a fix the PR is waiting for testing ( https://github.com/BlazingDB/blazingdb-ral/pull/184 ) So we hope today we will push this into develop ;) cc @rommelDB @Christian8491

**Comment by aucahuasi** [comment] 2019-10-09 21:43
Hi @mlahir1 PR #187 was merged into develop, could you please test again? 

Note: thanks @rommelDB @Christian8491

**Closed** 2019-10-21 20:00 UTC
